# Script to test write_console and if all functions works

d = 37  # Left Key

write_console("swapSprite : "..swap_sprite(37, 0, 1))
write_console("getElement : "..get_element(d, 1))
write_console("isInMap : "..is_in_map(get_pos_x(), get_pos_y(), get_map_size_x(), get_map_size_y(), d, 1))
write_console("writeConsole : "..write_console(1))
write_console("loadLevel : "..load_level(1))
write_console("nextLevel : "..next_level())
write_console("getMapSizeX : "..get_map_size_x())
write_console("getMapSizeY : "..get_map_size_y())
write_console("getPosX : "..get_pos_x())
write_console("getPosY : "..get_pos_y())
write_console("openDoor : "..open_door())
write_console("closeDoor : "..close_door())
write_console("isDoorOpen : "..is_door_open())
write_console("getObjectives : "..get_objectives())
write_console("takeObjective : "..take_objective())
write_console("getCurrentLevelName : "..get_current_level_name())
write_console("getLevelName : "..get_level_name(1))
write_console("getMusicIndex : "..get_music_index('pokemon.mp3'))
write_console("getCurrentMusicName : "..get_current_music_name())
write_console("getCurrentMusicIndex : "..get_current_music_index())
write_console("getMusicName : "..get_music_name(0))
write_console("playMusicNamed : "..play_music_named('pokemon.mp3'))
write_console("playMusicIndex : "..play_music_index(3))
write_console(wait_until_key_pressed())